// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_100_extra_words = "CgkIw4yNlc4WEAIQGw"; // <GPGSID>
        public const string achievement_extra_word = "CgkIw4yNlc4WEAIQMA"; // <GPGSID>
        public const string achievement_7_letters = "CgkIw4yNlc4WEAIQBw"; // <GPGSID>
        public const string achievement_500_word_searches = "CgkIw4yNlc4WEAIQOA"; // <GPGSID>
        public const string achievement_10_word_searches = "CgkIw4yNlc4WEAIQMw"; // <GPGSID>
        public const string achievement_50_levels_passed = "CgkIw4yNlc4WEAIQIw"; // <GPGSID>
        public const string achievement_10000_levels_passed = "CgkIw4yNlc4WEAIQKQ"; // <GPGSID>
        public const string achievement_100000_word_searches = "CgkIw4yNlc4WEAIQPA"; // <GPGSID>
        public const string achievement_18_letters = "CgkIw4yNlc4WEAIQEg"; // <GPGSID>
        public const string achievement_10000_word_searches = "CgkIw4yNlc4WEAIQOw"; // <GPGSID>
        public const string achievement_4_letters = "CgkIw4yNlc4WEAIQBA"; // <GPGSID>
        public const string achievement_first_level = "CgkIw4yNlc4WEAIQMQ"; // <GPGSID>
        public const string achievement_10_levels_passed = "CgkIw4yNlc4WEAIQIQ"; // <GPGSID>
        public const string achievement_11_letters = "CgkIw4yNlc4WEAIQCw"; // <GPGSID>
        public const string achievement_5000_word_searches = "CgkIw4yNlc4WEAIQOg"; // <GPGSID>
        public const string leaderboard_unlocked_letters = "CgkIw4yNlc4WEAIQQQ"; // <GPGSID>
        public const string achievement_300_levels_passed = "CgkIw4yNlc4WEAIQPQ"; // <GPGSID>
        public const string achievement_10_letters = "CgkIw4yNlc4WEAIQCg"; // <GPGSID>
        public const string achievement_beta_tester = "CgkIw4yNlc4WEAIQGA"; // <GPGSID>
        public const string achievement_19_letters = "CgkIw4yNlc4WEAIQEw"; // <GPGSID>
        public const string achievement_8_letters = "CgkIw4yNlc4WEAIQCA"; // <GPGSID>
        public const string leaderboard_words = "CgkIw4yNlc4WEAIQPg"; // <GPGSID>
        public const string achievement_12_letters = "CgkIw4yNlc4WEAIQDA"; // <GPGSID>
        public const string achievement_1000_extra_words = "CgkIw4yNlc4WEAIQHg"; // <GPGSID>
        public const string achievement_9_letters = "CgkIw4yNlc4WEAIQCQ"; // <GPGSID>
        public const string achievement_malinois = "CgkIw4yNlc4WEAIQLA"; // <GPGSID>
        public const string achievement_300_extra_words = "CgkIw4yNlc4WEAIQHA"; // <GPGSID>
        public const string achievement_beagle = "CgkIw4yNlc4WEAIQLQ"; // <GPGSID>
        public const string achievement_300_word_searches = "CgkIw4yNlc4WEAIQNw"; // <GPGSID>
        public const string achievement_word_search = "CgkIw4yNlc4WEAIQMg"; // <GPGSID>
        public const string achievement_100_word_searches = "CgkIw4yNlc4WEAIQNg"; // <GPGSID>
        public const string achievement_doberman = "CgkIw4yNlc4WEAIQLg"; // <GPGSID>
        public const string achievement_2000_levels_passed = "CgkIw4yNlc4WEAIQJw"; // <GPGSID>
        public const string achievement_13_letters = "CgkIw4yNlc4WEAIQDQ"; // <GPGSID>
        public const string achievement_500_levels_passed = "CgkIw4yNlc4WEAIQJQ"; // <GPGSID>
        public const string achievement_1000_word_searches = "CgkIw4yNlc4WEAIQOQ"; // <GPGSID>
        public const string leaderboard_unlocked_partners = "CgkIw4yNlc4WEAIQQg"; // <GPGSID>
        public const string achievement_500_extra_words = "CgkIw4yNlc4WEAIQHQ"; // <GPGSID>
        public const string achievement_20_levels_passed = "CgkIw4yNlc4WEAIQIg"; // <GPGSID>
        public const string achievement_10000_extra_words = "CgkIw4yNlc4WEAIQHw"; // <GPGSID>
        public const string leaderboard_passed_levels = "CgkIw4yNlc4WEAIQAQ"; // <GPGSID>
        public const string leaderboard_searched_words = "CgkIw4yNlc4WEAIQQA"; // <GPGSID>
        public const string achievement_50_word_searches = "CgkIw4yNlc4WEAIQNQ"; // <GPGSID>
        public const string achievement_20000_levels_passed = "CgkIw4yNlc4WEAIQKg"; // <GPGSID>
        public const string achievement_golden_chicken = "CgkIw4yNlc4WEAIQLw"; // <GPGSID>
        public const string achievement_10_extra_words = "CgkIw4yNlc4WEAIQGQ"; // <GPGSID>
        public const string achievement_14_letters = "CgkIw4yNlc4WEAIQDg"; // <GPGSID>
        public const string achievement_6_letters = "CgkIw4yNlc4WEAIQBg"; // <GPGSID>
        public const string achievement_16_letters = "CgkIw4yNlc4WEAIQEA"; // <GPGSID>
        public const string achievement_21_letters = "CgkIw4yNlc4WEAIQFQ"; // <GPGSID>
        public const string achievement_100000_extra_words = "CgkIw4yNlc4WEAIQIA"; // <GPGSID>
        public const string achievement_50_extra_words = "CgkIw4yNlc4WEAIQGg"; // <GPGSID>
        public const string achievement_20_letters = "CgkIw4yNlc4WEAIQFA"; // <GPGSID>
        public const string achievement_20_word_searches = "CgkIw4yNlc4WEAIQNA"; // <GPGSID>
        public const string achievement_100_levels_passed = "CgkIw4yNlc4WEAIQJA"; // <GPGSID>
        public const string achievement_5000_levels_passed = "CgkIw4yNlc4WEAIQKA"; // <GPGSID>
        public const string achievement_15_letters = "CgkIw4yNlc4WEAIQDw"; // <GPGSID>
        public const string achievement_22_letters = "CgkIw4yNlc4WEAIQFg"; // <GPGSID>
        public const string leaderboard_extra_words = "CgkIw4yNlc4WEAIQPw"; // <GPGSID>
        public const string achievement_1000_levels_passed = "CgkIw4yNlc4WEAIQJg"; // <GPGSID>
        public const string achievement_5_letters = "CgkIw4yNlc4WEAIQBQ"; // <GPGSID>
        public const string achievement_17_letters = "CgkIw4yNlc4WEAIQEQ"; // <GPGSID>
        public const string achievement_rating = "CgkIw4yNlc4WEAIQFw"; // <GPGSID>

}

